//! Emits a `Column::*` enum augmentation + `as_str()` accessor +
//! `from_name(&str)` string lookup + `IntoColumn` impl. The `Column`
//! enum itself is generated by SeaORM's `DeriveEntityModel` in
//! `derive_seaorm.rs`; here we attach inherent methods and the
//! `IntoColumn` bridge so users get a typed-and-stringy column API.
//!
//! The typed variants are used by builder methods that accept
//! `impl IntoColumn`; the string lookup is the runtime escape hatch
//! (`Column::from_name("email")`).

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::Result;

use super::parse::ModelInput;

/// `snake_case` -> `CamelCase` conversion. Public so other macro
/// modules (T7a's `casts.rs`) can reuse it.
pub fn to_camel(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper = true;
    for ch in snake.chars() {
        if ch == '_' {
            upper = true;
        } else if upper {
            out.push(ch.to_ascii_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

pub fn emit(input: &ModelInput) -> Result<TokenStream> {
    let fields = match &input.item.fields {
        syn::Fields::Named(named) => &named.named,
        _ => unreachable!("validated in derive_seaorm"),
    };

    let mut variant_idents = Vec::new();
    let mut variant_strs = Vec::new();
    for f in fields {
        let ident = f.ident.as_ref().expect("named");
        let snake = ident.to_string();
        let camel = to_camel(&snake);
        variant_idents.push(format_ident!("{camel}"));
        variant_strs.push(snake);
    }

    Ok(quote! {
        impl Column {
            /// Snake-case column name as written in SQL.
            pub fn as_str(&self) -> &'static str {
                match self {
                    #(Column::#variant_idents => #variant_strs,)*
                }
            }

            /// Look a column up by its snake-case name. `None` for
            /// non-existent names.
            pub fn from_name(name: &str) -> Option<Self> {
                match name {
                    #(#variant_strs => Some(Column::#variant_idents),)*
                    _ => None,
                }
            }

            /// Iterate every column on the model. Convenience wrapper
            /// over the SeaORM `Iterable` impl that the
            /// DeriveEntityModel macro provides.
            pub fn iter() -> impl ::core::iter::Iterator<Item = Column> {
                <Column as ::suprnova::Iterable>::iter()
            }
        }

        // IntoColumn impl — lets typed Column variants work alongside
        // strings throughout the Builder API (filter, order_by, etc.).
        impl ::suprnova::eloquent::builder::IntoColumn for Column {
            fn col_name(self) -> String {
                self.as_str().to_string()
            }
        }
    })
}
