//! Parses `#[suprnova::model(table = "...", primary_key = "...", ...)]`
//! into a structured representation other modules emit code from.

use proc_macro2::{Ident, Span, TokenStream};
use syn::{
    parse2, parse::Parse, parse::ParseStream, Expr, ItemStruct, LitBool, LitStr, Result, Token,
    Type,
};

// ---- Relation declarations (Phase 10B T1) ---------------------------------
//
// The macro accepts a `relations = { name: Kind<Target>, ... }` body and
// parses it into a list of [`RelationDecl`]. T1 ships the parser + the
// dispatcher skeleton; T2-T7 emit per-kind relation methods.
//
// The `MorphTo { targets = [Post, Video] }` shape is special-cased
// because `MorphTo` doesn't carry a single concrete target type —
// the targets live as a separate enumeration. The other ten kinds all
// follow `Kind<Target>` or `Kind<Target, Through>`.

/// One declared relation, e.g. `posts: HasMany<Post>` or
/// `roles: BelongsToMany<Role, RoleUserPivot> { with_pivot = [...] }`.
///
/// T1 ships the AST + parser. T2-T7 emit relation methods from the
/// `through` and `options` fields; `#[allow(dead_code)]` keeps them
/// quiet until those tasks wire them in.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct RelationDecl {
    /// The relation name as the user declared it (e.g. `"posts"`).
    /// Drives the dispatcher `match` and the inventory entry name.
    pub name: Ident,
    /// Which Eloquent flavour this is.
    pub kind: RelationKindAttr,
    /// Concrete target type — e.g. `Post` in `HasMany<Post>`. For
    /// `MorphTo` declarations this is unused (set to `()` by the
    /// parser as a placeholder); the actual targets live in
    /// `options` as `RelationOpt::MorphTargets`.
    pub target: Type,
    /// For `BelongsToMany` and the `*ToMany` polymorphic variants,
    /// this carries the intermediate Pivot model. For `HasOneThrough`
    /// / `HasManyThrough` it carries the intermediate model `B`.
    /// `None` for the remaining kinds.
    pub through: Option<Type>,
    /// Per-relation options (FK / LK overrides, `with_pivot`,
    /// `with_default`, `morph_name`, etc.). Order preserved.
    pub options: Vec<RelationOpt>,
}

/// Eloquent relation flavour as written in the `relations = { ... }`
/// body. Mirrors [`crate::eloquent::RelationKind`] but lives in the
/// proc-macro crate as a parse-time AST node.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RelationKindAttr {
    HasOne,
    BelongsTo,
    HasMany,
    BelongsToMany,
    HasOneThrough,
    HasManyThrough,
    MorphTo,
    MorphOne,
    MorphMany,
    MorphToMany,
    MorphedByMany,
}

impl RelationKindAttr {
    /// Match a kind name written in the macro body
    /// (`HasMany`, `MorphTo`, ...) to the AST variant. Returns
    /// `None` for unknown kinds — the parser turns that into a clear
    /// compile error pointing at the offending ident.
    pub fn from_ident(s: &str) -> Option<Self> {
        Some(match s {
            "HasOne" => Self::HasOne,
            "BelongsTo" => Self::BelongsTo,
            "HasMany" => Self::HasMany,
            "BelongsToMany" => Self::BelongsToMany,
            "HasOneThrough" => Self::HasOneThrough,
            "HasManyThrough" => Self::HasManyThrough,
            "MorphTo" => Self::MorphTo,
            "MorphOne" => Self::MorphOne,
            "MorphMany" => Self::MorphMany,
            "MorphToMany" => Self::MorphToMany,
            "MorphedByMany" => Self::MorphedByMany,
            _ => return None,
        })
    }

    /// Whether this kind expects a second generic argument (the Pivot
    /// for many-to-many, or the intermediate model for Through).
    pub fn needs_through(&self) -> bool {
        matches!(
            self,
            Self::BelongsToMany
                | Self::HasOneThrough
                | Self::HasManyThrough
                | Self::MorphToMany
                | Self::MorphedByMany
        )
    }

    /// Whether this kind allows a generic argument list at all.
    /// `MorphTo` is the lone exception — it carries no `<Target>`
    /// because the target is a per-family enum generated by T6.
    pub fn allows_generics(&self) -> bool {
        !matches!(self, Self::MorphTo)
    }
}

/// One inline option declared inside `Kind<...> { ... }`.
///
/// T1 ships the AST + parser. T2-T7 consume the variants when emitting
/// concrete relation methods (e.g. `WithDefault` lands on `BelongsTo`
/// in T2; `WithPivot` / `WithTimestamps` on `BelongsToMany` in T4).
/// The `#[allow(dead_code)]` keeps the variants quiet until the
/// downstream tasks wire them up.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub enum RelationOpt {
    /// `fk = "owner_id"` — override the column on the child table.
    ForeignKey(String),
    /// `lk = "id"` — override the column on the parent table.
    LocalKey(String),
    /// `with_pivot = ["assigned_at", "...", ...]` — extra columns to
    /// surface on the pivot row.
    WithPivot(Vec<String>),
    /// `with_timestamps` (bare flag) — touch `created_at` /
    /// `updated_at` on the pivot row.
    WithTimestamps,
    /// `with_default = || User { ... }` — closure producing a default
    /// value when `BelongsTo` finds no row.
    WithDefault(Expr),
    /// `scope = |q| q.filter(...)` — apply a filter at query time.
    Scope(Expr),
    /// `morph_name = "commentable"` — sets the morph family name on
    /// `MorphOne`/`MorphMany`/`MorphToMany`/`MorphedByMany`. For
    /// `MorphTo`, the family name comes from the declared relation
    /// name itself, not this option.
    MorphName(String),
    /// `targets = [Post, Video]` — the list of concrete morph targets
    /// for `MorphTo` declarations. Used by T6 to emit the per-family
    /// `<Name>Morph` enum.
    MorphTargets(Vec<Type>),
    /// `first_key = "country_id"` — `HasManyThrough` override.
    FirstKey(String),
    /// `second_key = "user_id"` — `HasManyThrough` override.
    SecondKey(String),
    /// `pivot_table = "role_user"` — explicit pivot table name for
    /// `BelongsToMany`. Defaults to the pivot type's
    /// `<P as EloquentModel>::TABLE` const when omitted.
    PivotTable(String),
    /// `pivot_foreign_key = "user_id"` — pivot column pointing at the
    /// parent (`L`). Defaults to `<snake(parent_struct)>_id`.
    PivotForeignKey(String),
    /// `pivot_related_key = "role_id"` — pivot column pointing at the
    /// related row (`R`). Defaults to `<snake(target_struct)>_id`.
    PivotRelatedKey(String),
}

/// The parsed `#[model(...)]` attribute plus the struct definition.
pub struct ModelInput {
    pub item: ItemStruct,
    pub table: String,
    pub primary_key: String,
    #[allow(dead_code)] // T4+ — used when typed CRUD lifecycle wires through.
    pub key_type: Type,
    pub auto_increment: bool,
    #[allow(dead_code)] // T4+ — multi-connection routing in derive_eloquent.
    pub connection: String,
    // Slots filled by later tasks (Phase 10A T6/T7a/T9/T10):
    #[allow(dead_code)]
    pub fillable: Option<Vec<String>>,
    #[allow(dead_code)]
    pub guarded: Option<Vec<String>>,
    #[allow(dead_code)]
    pub casts: Vec<(Ident, Type)>,
    #[allow(dead_code)]
    pub timestamps: bool,
    #[allow(dead_code)]
    pub created_at: String,
    #[allow(dead_code)]
    pub updated_at: String,
    #[allow(dead_code)]
    pub soft_deletes: bool,
    #[allow(dead_code)]
    pub soft_deletes_column: String,
    #[allow(dead_code)]
    pub appends: Vec<String>,
    #[allow(dead_code)]
    pub hidden: Vec<String>,
    #[allow(dead_code)]
    pub visible: Option<Vec<String>>,
    #[allow(dead_code)]
    pub mutators: Vec<String>,
    #[allow(dead_code)]
    pub touches: Vec<String>,
    /// Phase 10B T1 — parsed `relations = { ... }` body. `None` when
    /// the attribute is omitted entirely (no relations declared on
    /// this model); `Some(vec![])` for the explicit empty form
    /// `relations = {}` (legal — still wires the four dispatcher
    /// skeletons).
    pub relations: Option<Vec<RelationDecl>>,
}

impl ModelInput {
    pub fn parse(attr: TokenStream, item: TokenStream) -> Result<Self> {
        let item: ItemStruct = parse2(item)?;
        let attrs = parse2::<ModelAttrs>(attr)?;
        let struct_name = item.ident.to_string();

        let table = attrs.table.unwrap_or_else(|| pluralize_snake(&struct_name));
        let primary_key = attrs.primary_key.unwrap_or_else(|| "id".to_string());
        let key_type = attrs
            .key_type
            .unwrap_or_else(|| syn::parse_str("i64").expect("i64 parses"));
        let auto_increment = attrs.auto_increment.unwrap_or(true);
        let connection = attrs.connection.unwrap_or_else(|| "default".to_string());
        let timestamps_default = attrs.timestamps.unwrap_or(true);
        let created_at = attrs.created_at.unwrap_or_else(|| "created_at".to_string());
        let updated_at = attrs.updated_at.unwrap_or_else(|| "updated_at".to_string());
        let soft_deletes = attrs.soft_deletes.unwrap_or(false);
        let soft_deletes_column = attrs
            .soft_deletes_column
            .unwrap_or_else(|| "deleted_at".to_string());

        if attrs.fillable.is_some() && attrs.guarded.is_some() {
            return Err(syn::Error::new(
                Span::call_site(),
                "cannot specify both `fillable` and `guarded` on the same model",
            ));
        }

        // T8 — `hidden` is a denylist, `visible` an allowlist. Both at
        // once is incoherent (one says "drop these", the other "keep
        // only these") and Laravel rejects the same combination via
        // `$hidden` / `$visible` semantics.
        if !attrs.hidden.as_ref().is_none_or(Vec::is_empty)
            && attrs.visible.as_ref().is_some_and(|v| !v.is_empty())
        {
            return Err(syn::Error::new(
                Span::call_site(),
                "cannot specify both `hidden` and `visible` on the same model",
            ));
        }

        // T9 — auto-detect timestamp columns from the struct fields.
        //
        //   user attribute       | struct has BOTH      | exactly ONE     | NEITHER
        //   ---------------------+----------------------+-----------------+---------
        //   timestamps = false   | disabled             | disabled        | disabled
        //   timestamps (default) | enabled              | compile_error!  | disabled
        //
        // The default-enabled case used to fail at compile time if the
        // struct lacked `created_at` / `updated_at` (the macro emitted
        // `am.created_at = Set(now)` against a non-existent ActiveModel
        // field). Auto-detect lets users skip the `timestamps = false`
        // opt-out ceremony for join tables / pivots / no-history models.
        // The exactly-one case still errors loudly because it's almost
        // certainly a typo (e.g. `craeted_at`) — silently skipping
        // there would mask the bug.
        let field_names: std::collections::HashSet<String> = match &item.fields {
            syn::Fields::Named(named) => named
                .named
                .iter()
                .filter_map(|f| f.ident.as_ref().map(|i| i.to_string()))
                // The relations emitter auto-injects `__eager` and
                // `__pivot` — they're not user-declared columns, so
                // exclude them from the timestamp-presence check.
                .filter(|name| name != "__eager" && name != "__pivot")
                .collect(),
            _ => std::collections::HashSet::new(),
        };
        let has_created = field_names.contains(&created_at);
        let has_updated = field_names.contains(&updated_at);
        let timestamps = if !timestamps_default {
            false
        } else {
            match (has_created, has_updated) {
                (true, true) => true,
                (false, false) => false,
                _ => {
                    return Err(syn::Error::new_spanned(
                        &item.ident,
                        format!(
                            "model has only one of `{}` / `{}`. Eloquent timestamps need both \
                             columns (or neither). Add the missing field, or set \
                             `#[model(timestamps = false)]` to disable timestamp tracking \
                             entirely.",
                            created_at, updated_at,
                        ),
                    ));
                }
            }
        };

        // Auto-inject `AsDateTime` / `AsOptionalDateTime` casts on
        // every field whose declared type is `DateTime<Utc>` /
        // `Option<DateTime<Utc>>`. The cast does double duty: it
        // unblocks SeaORM's `DeriveEntityModel` parser (which
        // mis-parses bare `DateTime<Utc>` as `NaiveDateTime` since
        // SeaORM's prelude shadows the chrono name and the parser
        // can't see through generics), AND it wires the same Runtime
        // <-> Storage bridge the rest of the cast machinery uses, so
        // `.touch()` / auto-set injection / soft-delete tombstones
        // don't need parallel datetime-formatting paths.
        //
        // The auto-inject is per-field type, NOT per-column-name —
        // so user-defined columns like `pub last_seen_at:
        // DateTime<Utc>` get the cast just like framework-managed
        // `created_at` / `updated_at` / `deleted_at` do. Subsumes
        // the T9 / T10 column-name-keyed injections that existed
        // before this polish.
        //
        // Fields with a user-declared cast are skipped — explicit
        // intent wins. So `casts = { foo = AsImmutableDateTime }`
        // overrides the default `AsDateTime` on that field.
        let mut casts = attrs.casts.unwrap_or_default();
        if let syn::Fields::Named(named) = &item.fields {
            for field in &named.named {
                let ident = match field.ident.as_ref() {
                    Some(i) => i,
                    None => continue,
                };
                let name = ident.to_string();
                // PK isn't cast-routed (see derive_seaorm.rs — PK
                // fields keep their declared type), so even if a
                // PK happened to be DateTime<Utc> the injection
                // would be a no-op. Skipping explicitly clarifies
                // intent. Same logic for the auto-injected
                // `__eager` / `__pivot` fields the relations emitter
                // adds — they're not database columns and never
                // need a cast.
                if name == primary_key || name == "__eager" || name == "__pivot" {
                    continue;
                }
                if casts.iter().any(|(i, _)| i == &name) {
                    // User already declared a cast for this field —
                    // their intent wins.
                    continue;
                }
                match classify_datetime(&field.ty) {
                    DateTimeShape::DateTime => {
                        let ty: Type = syn::parse_str("::suprnova::AsDateTime").expect(
                            "::suprnova::AsDateTime parses — Suprnova lib re-exports this type",
                        );
                        casts.push((ident.clone(), ty));
                    }
                    DateTimeShape::OptionalDateTime => {
                        let ty: Type = syn::parse_str("::suprnova::AsOptionalDateTime").expect(
                            "::suprnova::AsOptionalDateTime parses — Suprnova lib re-exports this type",
                        );
                        casts.push((ident.clone(), ty));
                    }
                    DateTimeShape::Other => {}
                }
            }
        }

        Ok(Self {
            item,
            table,
            primary_key,
            key_type,
            auto_increment,
            connection,
            fillable: attrs.fillable,
            guarded: attrs.guarded,
            casts,
            timestamps,
            created_at,
            updated_at,
            soft_deletes,
            soft_deletes_column,
            appends: attrs.appends.unwrap_or_default(),
            hidden: attrs.hidden.unwrap_or_default(),
            visible: attrs.visible,
            mutators: attrs.mutators.unwrap_or_default(),
            touches: attrs.touches.unwrap_or_default(),
            relations: attrs.relations,
        })
    }

    pub fn module_name(&self) -> Ident {
        let s = to_snake(&self.item.ident.to_string());
        Ident::new(&s, self.item.ident.span())
    }

    pub fn struct_name_str(&self) -> String {
        self.item.ident.to_string()
    }

    pub fn struct_def(&self) -> &ItemStruct {
        &self.item
    }

    /// Look up the cast type declared for a field. Used by `casts::emit`
    /// once T7a wires the cast pipeline.
    #[allow(dead_code)]
    pub fn cast_for_field(&self, name: &str) -> Option<&Type> {
        self.casts.iter().find_map(|(ident, ty)| {
            if ident == name { Some(ty) } else { None }
        })
    }
}

/// Outcome of [`classify_datetime`] — used to decide which datetime
/// cast (if any) to auto-inject onto a field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DateTimeShape {
    /// `DateTime<Utc>` (in any qualified form).
    DateTime,
    /// `Option<DateTime<Utc>>` (in any qualified form).
    OptionalDateTime,
    /// Anything else — no auto-injection.
    Other,
}

/// Recognise `DateTime<Utc>` and `Option<DateTime<Utc>>` in their
/// common qualified forms.
///
/// Conservative on purpose: only fires when the path ends in
/// `DateTime` with a single generic argument whose last path segment
/// is `Utc`, OR when the path ends in `Option` with a single generic
/// argument that itself classifies as `DateTime`.
///
/// Forms handled:
/// - `DateTime<Utc>`
/// - `chrono::DateTime<Utc>` / `::chrono::DateTime<Utc>`
/// - `DateTime<chrono::Utc>` / `chrono::DateTime<chrono::Utc>`
/// - `Option<DateTime<Utc>>` (and qualified inner / outer paths)
///
/// Forms NOT handled (treated as `Other`):
/// - `DateTime<Local>` / `DateTime<FixedOffset>` — Suprnova
///   standardises on UTC at the storage boundary.
/// - `Vec<DateTime<Utc>>` / `HashMap<_, DateTime<Utc>>` — collections
///   need their own cast (e.g. `AsArray<DateTime<Utc>>` written
///   explicitly by the user).
/// - Type aliases (`type Stamp = DateTime<Utc>; pub foo: Stamp`) —
///   syn can't resolve aliases at macro time; the user can declare
///   the cast explicitly.
fn classify_datetime(ty: &Type) -> DateTimeShape {
    let Type::Path(path) = ty else {
        return DateTimeShape::Other;
    };
    let Some(last) = path.path.segments.last() else {
        return DateTimeShape::Other;
    };
    match last.ident.to_string().as_str() {
        "DateTime" => {
            // Must have exactly one generic argument whose last
            // path segment is `Utc`.
            let syn::PathArguments::AngleBracketed(args) = &last.arguments else {
                return DateTimeShape::Other;
            };
            if args.args.len() != 1 {
                return DateTimeShape::Other;
            }
            let Some(syn::GenericArgument::Type(Type::Path(tz_path))) = args.args.first() else {
                return DateTimeShape::Other;
            };
            let Some(tz_last) = tz_path.path.segments.last() else {
                return DateTimeShape::Other;
            };
            if tz_last.ident == "Utc"
                && matches!(tz_last.arguments, syn::PathArguments::None)
            {
                DateTimeShape::DateTime
            } else {
                DateTimeShape::Other
            }
        }
        "Option" => {
            let syn::PathArguments::AngleBracketed(args) = &last.arguments else {
                return DateTimeShape::Other;
            };
            if args.args.len() != 1 {
                return DateTimeShape::Other;
            }
            let Some(syn::GenericArgument::Type(inner)) = args.args.first() else {
                return DateTimeShape::Other;
            };
            // Promote `DateTime<Utc>` to `OptionalDateTime`; anything
            // else (including nested `Option<Option<DateTime<Utc>>>`)
            // falls through to `Other` — those shapes don't have a
            // sensible default cast.
            if classify_datetime(inner) == DateTimeShape::DateTime {
                DateTimeShape::OptionalDateTime
            } else {
                DateTimeShape::Other
            }
        }
        _ => DateTimeShape::Other,
    }
}

/// Helper — convert `CamelCase` → `snake_case`.
pub fn to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.char_indices() {
        if ch.is_uppercase() && i != 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}

/// Naive pluralizer — good enough for the common cases users will hit.
/// Override with explicit `table = "..."` for irregulars.
fn pluralize_snake(struct_name: &str) -> String {
    let snake = to_snake(struct_name);
    if snake.ends_with('s') || snake.ends_with("ch") || snake.ends_with("sh") || snake.ends_with('x') || snake.ends_with('z') {
        format!("{snake}es")
    } else if snake.ends_with('y') && snake.len() > 1 {
        let stem = &snake[..snake.len() - 1];
        let prev = snake.chars().nth(snake.len() - 2).unwrap();
        if matches!(prev, 'a' | 'e' | 'i' | 'o' | 'u') {
            format!("{snake}s")
        } else {
            format!("{stem}ies")
        }
    } else {
        format!("{snake}s")
    }
}

/// Internal parser for the comma-separated `name = value` attribute body.
#[derive(Default)]
struct ModelAttrs {
    table: Option<String>,
    primary_key: Option<String>,
    key_type: Option<Type>,
    auto_increment: Option<bool>,
    connection: Option<String>,
    fillable: Option<Vec<String>>,
    guarded: Option<Vec<String>>,
    casts: Option<Vec<(Ident, Type)>>,
    timestamps: Option<bool>,
    created_at: Option<String>,
    updated_at: Option<String>,
    soft_deletes: Option<bool>,
    soft_deletes_column: Option<String>,
    appends: Option<Vec<String>>,
    hidden: Option<Vec<String>>,
    visible: Option<Vec<String>>,
    mutators: Option<Vec<String>>,
    touches: Option<Vec<String>>,
    relations: Option<Vec<RelationDecl>>,
}

impl Parse for ModelAttrs {
    fn parse(input: ParseStream) -> Result<Self> {
        let mut out = ModelAttrs::default();
        if input.is_empty() {
            return Ok(out);
        }
        loop {
            let key: Ident = input.parse()?;
            // Flag-style attributes (no `=`):
            if matches!(key.to_string().as_str(), "soft_deletes" | "timestamps")
                && (input.is_empty() || input.peek(Token![,]))
            {
                match key.to_string().as_str() {
                    "soft_deletes" => out.soft_deletes = Some(true),
                    "timestamps" => out.timestamps = Some(true),
                    _ => unreachable!(),
                }
            } else {
                input.parse::<Token![=]>()?;
                match key.to_string().as_str() {
                    "table" => out.table = Some(input.parse::<LitStr>()?.value()),
                    "primary_key" => out.primary_key = Some(input.parse::<LitStr>()?.value()),
                    "key_type" => {
                        let lit = input.parse::<LitStr>()?;
                        out.key_type = Some(syn::parse_str::<Type>(&lit.value()).map_err(|e| {
                            syn::Error::new(lit.span(), format!("invalid `key_type` Rust type: {e}"))
                        })?);
                    }
                    "auto_increment" => out.auto_increment = Some(input.parse::<LitBool>()?.value),
                    "connection" => out.connection = Some(input.parse::<LitStr>()?.value()),
                    "fillable" => out.fillable = Some(parse_str_array(input)?),
                    "guarded" => out.guarded = Some(parse_str_array(input)?),
                    "casts" => out.casts = Some(parse_casts_map(input)?),
                    "timestamps" => out.timestamps = Some(input.parse::<LitBool>()?.value),
                    "created_at" => out.created_at = Some(input.parse::<LitStr>()?.value()),
                    "updated_at" => out.updated_at = Some(input.parse::<LitStr>()?.value()),
                    "soft_deletes" => out.soft_deletes = Some(input.parse::<LitBool>()?.value),
                    "soft_deletes_column" => out.soft_deletes_column = Some(input.parse::<LitStr>()?.value()),
                    "appends" => out.appends = Some(parse_str_array(input)?),
                    "hidden" => out.hidden = Some(parse_str_array(input)?),
                    "visible" => out.visible = Some(parse_str_array(input)?),
                    "mutators" => out.mutators = Some(parse_str_array(input)?),
                    "touches" => out.touches = Some(parse_str_array(input)?),
                    "relations" => out.relations = Some(parse_relations_map(input)?),
                    other => {
                        return Err(syn::Error::new(
                            key.span(),
                            format!("unknown `#[model]` attribute: `{other}`"),
                        ));
                    }
                }
            }
            if input.is_empty() {
                break;
            }
            input.parse::<Token![,]>()?;
            if input.is_empty() {
                break;
            }
        }
        Ok(out)
    }
}

fn parse_str_array(input: ParseStream) -> Result<Vec<String>> {
    let content;
    syn::bracketed!(content in input);
    let mut out = Vec::new();
    while !content.is_empty() {
        out.push(content.parse::<LitStr>()?.value());
        if content.is_empty() {
            break;
        }
        content.parse::<Token![,]>()?;
    }
    Ok(out)
}

fn parse_casts_map(input: ParseStream) -> Result<Vec<(Ident, Type)>> {
    let content;
    syn::braced!(content in input);
    let mut entries = Vec::new();
    while !content.is_empty() {
        let field: Ident = content.parse()?;
        content.parse::<Token![=]>()?;
        let ty: Type = content.parse()?;
        entries.push((field, ty));
        if content.is_empty() { break; }
        content.parse::<Token![,]>()?;
    }
    Ok(entries)
}

/// Parse the `relations = { ... }` attribute body.
///
/// Grammar:
///
/// ```text
/// relations = {
///     name: Kind<Target>[, Through],
///     name: Kind<Target> { opt = val, flag, ... },
///     name: MorphTo { targets = [T1, T2], ... },
///     ...
/// }
/// ```
///
/// Each entry is `<name>: <KindGeneric>` followed optionally by
/// `{ <opt>, ... }`. `KindGeneric` is `Ident<Type[, Type]>` — the
/// kind ident must match one of the 11 [`RelationKindAttr`]
/// variants; the parser produces a clear error otherwise.
///
/// Options inside `{}` are comma-separated `<key> = <value>` pairs
/// (or bare flags like `with_timestamps`). Unknown options surface as
/// a clear compile error pointing at the option name.
fn parse_relations_map(input: ParseStream) -> Result<Vec<RelationDecl>> {
    let content;
    syn::braced!(content in input);
    let mut out = Vec::new();
    while !content.is_empty() {
        let decl = parse_one_relation(&content)?;
        out.push(decl);
        if content.is_empty() {
            break;
        }
        content.parse::<Token![,]>()?;
    }
    Ok(out)
}

fn parse_one_relation(input: ParseStream) -> Result<RelationDecl> {
    let name: Ident = input.parse()?;
    input.parse::<Token![:]>()?;

    // Parse the kind ident — `HasMany`, `BelongsToMany`, `MorphTo`, ...
    let kind_ident: Ident = input.parse()?;
    let kind_str = kind_ident.to_string();
    let kind = RelationKindAttr::from_ident(&kind_str).ok_or_else(|| {
        syn::Error::new(
            kind_ident.span(),
            format!(
                "unknown relation kind `{kind_str}`. Expected one of: HasOne, BelongsTo, \
                 HasMany, BelongsToMany, HasOneThrough, HasManyThrough, MorphTo, MorphOne, \
                 MorphMany, MorphToMany, MorphedByMany.",
            ),
        )
    })?;

    // Parse the generic argument list. `MorphTo` has none; every
    // other kind has one or two generic types.
    let (target, through) = if kind.allows_generics() {
        if !input.peek(Token![<]) {
            return Err(syn::Error::new(
                kind_ident.span(),
                format!("`{kind_str}` requires a generic target type, e.g. `{kind_str}<Target>`"),
            ));
        }
        input.parse::<Token![<]>()?;
        let target: Type = input.parse()?;
        let through = if input.peek(Token![,]) {
            input.parse::<Token![,]>()?;
            let through_ty: Type = input.parse()?;
            Some(through_ty)
        } else {
            None
        };
        input.parse::<Token![>]>()?;

        if kind.needs_through() && through.is_none() {
            return Err(syn::Error::new(
                kind_ident.span(),
                format!(
                    "`{kind_str}` requires a second generic argument (the intermediate \
                     model / pivot), e.g. `{kind_str}<Target, Through>`",
                ),
            ));
        }
        if !kind.needs_through() && through.is_some() {
            return Err(syn::Error::new(
                kind_ident.span(),
                format!("`{kind_str}` takes one generic argument, not two"),
            ));
        }
        (target, through)
    } else {
        // `MorphTo` — placeholder unit target; the real per-family
        // enum is generated by T6 from the `targets = [...]` option.
        (syn::parse_str::<Type>("()").expect("() parses"), None)
    };

    // Optional `{ opts, ... }` block.
    let options = if input.peek(syn::token::Brace) {
        parse_relation_options(input, kind)?
    } else {
        Vec::new()
    };

    // `MorphTo` is the one relation kind that has no concrete target
    // type at the declaration site — the per-family enum is generated
    // by T6 from the `targets = [...]` option. Without that option
    // T6 has nothing to enumerate over, so the silent path would
    // surface as a confusing downstream error when the admin or
    // eager loader walks the morph family. Catch it here, at the
    // declaration site, with a span pointing at the `MorphTo` ident.
    if kind == RelationKindAttr::MorphTo
        && !options
            .iter()
            .any(|o| matches!(o, RelationOpt::MorphTargets(_)))
    {
        return Err(syn::Error::new(
            kind_ident.span(),
            "MorphTo relation requires `targets = [...]` listing the concrete morph target types",
        ));
    }

    Ok(RelationDecl {
        name,
        kind,
        target,
        through,
        options,
    })
}

fn parse_relation_options(input: ParseStream, kind: RelationKindAttr) -> Result<Vec<RelationOpt>> {
    let content;
    syn::braced!(content in input);
    let mut out = Vec::new();
    while !content.is_empty() {
        let key: Ident = content.parse()?;
        let key_str = key.to_string();

        // Bare flags (no `=`):
        if matches!(key_str.as_str(), "with_timestamps")
            && (content.is_empty() || content.peek(Token![,]))
        {
            out.push(RelationOpt::WithTimestamps);
        } else {
            content.parse::<Token![=]>()?;
            match key_str.as_str() {
                "fk" => {
                    let s: LitStr = content.parse()?;
                    out.push(RelationOpt::ForeignKey(s.value()));
                }
                "lk" => {
                    let s: LitStr = content.parse()?;
                    out.push(RelationOpt::LocalKey(s.value()));
                }
                "with_pivot" => {
                    let cols = parse_str_array(&content)?;
                    out.push(RelationOpt::WithPivot(cols));
                }
                "with_timestamps" => {
                    let b: LitBool = content.parse()?;
                    if b.value {
                        out.push(RelationOpt::WithTimestamps);
                    }
                }
                "with_default" => {
                    let expr: Expr = content.parse()?;
                    out.push(RelationOpt::WithDefault(expr));
                }
                "scope" => {
                    let expr: Expr = content.parse()?;
                    out.push(RelationOpt::Scope(expr));
                }
                "name" | "morph_name" => {
                    let s: LitStr = content.parse()?;
                    out.push(RelationOpt::MorphName(s.value()));
                }
                "targets" => {
                    if kind != RelationKindAttr::MorphTo {
                        return Err(syn::Error::new(
                            key.span(),
                            "`targets = [...]` is only valid on `MorphTo` relations",
                        ));
                    }
                    let types = parse_type_array(&content)?;
                    out.push(RelationOpt::MorphTargets(types));
                }
                "first_key" => {
                    let s: LitStr = content.parse()?;
                    out.push(RelationOpt::FirstKey(s.value()));
                }
                "second_key" => {
                    let s: LitStr = content.parse()?;
                    out.push(RelationOpt::SecondKey(s.value()));
                }
                "pivot_table" => {
                    let s: LitStr = content.parse()?;
                    out.push(RelationOpt::PivotTable(s.value()));
                }
                "pivot_foreign_key" => {
                    let s: LitStr = content.parse()?;
                    out.push(RelationOpt::PivotForeignKey(s.value()));
                }
                "pivot_related_key" => {
                    let s: LitStr = content.parse()?;
                    out.push(RelationOpt::PivotRelatedKey(s.value()));
                }
                other => {
                    return Err(syn::Error::new(
                        key.span(),
                        format!(
                            "unknown relation option `{other}`. Expected one of: fk, lk, \
                             with_pivot, with_timestamps, with_default, scope, name, targets, \
                             first_key, second_key, pivot_table, pivot_foreign_key, \
                             pivot_related_key.",
                        ),
                    ));
                }
            }
        }

        if content.is_empty() {
            break;
        }
        content.parse::<Token![,]>()?;
    }
    Ok(out)
}

/// Parse `[Type, Type, ...]` — the literal type list used by
/// `targets = [Post, Video]` on `MorphTo` declarations.
fn parse_type_array(input: ParseStream) -> Result<Vec<Type>> {
    let content;
    syn::bracketed!(content in input);
    let mut out = Vec::new();
    while !content.is_empty() {
        let ty: Type = content.parse()?;
        out.push(ty);
        if content.is_empty() {
            break;
        }
        content.parse::<Token![,]>()?;
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;

    #[test]
    fn parse_defaults_minimal() {
        let input = ModelInput::parse(
            quote! {},
            quote! { pub struct User { pub id: i64, pub name: String } },
        )
        .unwrap();
        assert_eq!(input.table, "users");
        assert_eq!(input.primary_key, "id");
        assert!(input.auto_increment);
        assert_eq!(input.connection, "default");
    }

    #[test]
    fn parse_explicit_table() {
        let input = ModelInput::parse(
            quote! { table = "people" },
            quote! { pub struct Person { pub id: i64 } },
        )
        .unwrap();
        assert_eq!(input.table, "people");
    }

    #[test]
    fn pluralize_handles_common_cases() {
        assert_eq!(pluralize_snake("User"), "users");
        assert_eq!(pluralize_snake("Post"), "posts");
        assert_eq!(pluralize_snake("Category"), "categories");
        assert_eq!(pluralize_snake("Holiday"), "holidays");
        assert_eq!(pluralize_snake("Box"), "boxes");
        assert_eq!(pluralize_snake("Match"), "matches");
        assert_eq!(pluralize_snake("Bus"), "buses");
    }

    #[test]
    fn fillable_and_guarded_conflict_errors() {
        let result = ModelInput::parse(
            quote! { fillable = ["a"], guarded = ["b"] },
            quote! { pub struct X { pub id: i64 } },
        );
        match result {
            Ok(_) => panic!("expected fillable + guarded conflict, got Ok"),
            Err(e) => assert!(
                e.to_string().contains("both `fillable` and `guarded`"),
                "unexpected error message: {e}",
            ),
        }
    }

    #[test]
    fn hidden_and_visible_conflict_errors() {
        // T8 — `hidden` is a denylist, `visible` an allowlist; the
        // pair is incoherent. Mirrors fillable + guarded mutual
        // exclusion.
        let result = ModelInput::parse(
            quote! { hidden = ["secret"], visible = ["name"] },
            quote! { pub struct X { pub id: i64, pub name: String, pub secret: String } },
        );
        match result {
            Ok(_) => panic!("expected hidden + visible conflict, got Ok"),
            Err(e) => assert!(
                e.to_string().contains("both `hidden` and `visible`"),
                "unexpected error message: {e}",
            ),
        }
    }

    #[test]
    fn parse_casts_attribute() {
        let input = ModelInput::parse(
            quote! { casts = { active = AsBool, tags = AsArray<String> } },
            quote! { pub struct X { pub id: i64, pub active: bool, pub tags: Vec<String> } },
        )
        .unwrap();
        assert_eq!(input.casts.len(), 2);
        assert_eq!(input.casts[0].0.to_string(), "active");
        assert_eq!(input.casts[1].0.to_string(), "tags");
    }

    #[test]
    fn timestamps_auto_detect_both_columns_enabled() {
        // Default `timestamps = true` + struct has both columns →
        // timestamps enabled + AsDateTime casts auto-injected.
        let input = ModelInput::parse(
            quote! {},
            quote! {
                pub struct User {
                    pub id: i64,
                    pub created_at: chrono::DateTime<chrono::Utc>,
                    pub updated_at: chrono::DateTime<chrono::Utc>,
                }
            },
        )
        .unwrap();
        assert!(input.timestamps);
        assert!(input.casts.iter().any(|(i, _)| i == "created_at"));
        assert!(input.casts.iter().any(|(i, _)| i == "updated_at"));
    }

    #[test]
    fn timestamps_auto_detect_neither_column_disabled() {
        // Default `timestamps = true` + struct has neither column →
        // auto-detect silently skips.
        let input = ModelInput::parse(
            quote! {},
            quote! { pub struct Pivot { pub id: i64, pub user_id: i64, pub role_id: i64 } },
        )
        .unwrap();
        assert!(!input.timestamps);
        assert!(input.casts.is_empty(), "no auto-injected casts on disabled timestamps");
    }

    #[test]
    fn timestamps_auto_detect_partial_errors() {
        // Default `timestamps = true` + struct has only updated_at →
        // compile error (typo guard).
        let result = ModelInput::parse(
            quote! {},
            quote! {
                pub struct Half {
                    pub id: i64,
                    pub updated_at: chrono::DateTime<chrono::Utc>,
                }
            },
        );
        match result {
            Ok(_) => panic!("expected partial-timestamps error, got Ok"),
            Err(e) => assert!(
                e.to_string().contains("only one of"),
                "unexpected error message: {e}",
            ),
        }
    }

    #[test]
    fn timestamps_false_disables_auto_management_but_keeps_type_bridge() {
        // `timestamps = false` disables the FRAMEWORK-MANAGED
        // bump-on-save behaviour, but `DateTime<Utc>` fields still
        // need the `AsDateTime` cast to bridge SeaORM's `NaiveDateTime`
        // parser shadow. The auto-inject is per-field-type now, not
        // per-column-name — so the casts still land, the runtime
        // injection in `into_active_model_for_update` just doesn't.
        let input = ModelInput::parse(
            quote! { timestamps = false },
            quote! {
                pub struct AuditLog {
                    pub id: i64,
                    pub created_at: chrono::DateTime<chrono::Utc>,
                    pub updated_at: chrono::DateTime<chrono::Utc>,
                }
            },
        )
        .unwrap();
        assert!(!input.timestamps, "framework-managed timestamps disabled");
        // Type-bridge casts still injected for both DateTime<Utc>
        // fields — without these the inner Model wouldn't compile.
        assert!(
            input.casts.iter().any(|(i, _)| i == "created_at"),
            "AsDateTime cast still injected for DateTime<Utc> field",
        );
        assert!(
            input.casts.iter().any(|(i, _)| i == "updated_at"),
            "AsDateTime cast still injected for DateTime<Utc> field",
        );
    }

    #[test]
    fn timestamps_custom_column_names() {
        // `created_at = "..."` / `updated_at = "..."` overrides apply
        // to both the field detection and the auto-cast injection.
        let input = ModelInput::parse(
            quote! { created_at = "creado_en", updated_at = "actualizado_en" },
            quote! {
                pub struct Post {
                    pub id: i64,
                    pub creado_en: chrono::DateTime<chrono::Utc>,
                    pub actualizado_en: chrono::DateTime<chrono::Utc>,
                }
            },
        )
        .unwrap();
        assert!(input.timestamps);
        assert_eq!(input.created_at, "creado_en");
        assert_eq!(input.updated_at, "actualizado_en");
        assert!(input.casts.iter().any(|(i, _)| i == "creado_en"));
        assert!(input.casts.iter().any(|(i, _)| i == "actualizado_en"));
    }

    #[test]
    fn timestamps_user_cast_override_preserved() {
        // If the user explicitly declares a cast for created_at /
        // updated_at, the macro doesn't replace it. AsImmutableDateTime
        // here would survive the auto-injection.
        let input = ModelInput::parse(
            quote! { casts = { created_at = AsImmutableDateTime } },
            quote! {
                pub struct Post {
                    pub id: i64,
                    pub created_at: chrono::DateTime<chrono::Utc>,
                    pub updated_at: chrono::DateTime<chrono::Utc>,
                }
            },
        )
        .unwrap();
        assert!(input.timestamps);
        let created_cast = input.casts.iter().find(|(i, _)| i == "created_at").unwrap();
        let ty_token = &created_cast.1;
        let ty = quote!(#ty_token).to_string();
        // The user's `AsImmutableDateTime` wins; auto-injection didn't
        // overwrite. (We don't probe the type literally to keep the
        // assertion robust against whitespace.)
        assert!(
            ty.contains("AsImmutableDateTime"),
            "expected user-declared AsImmutableDateTime, got: {ty}",
        );
        // updated_at still got auto-injected since the user only
        // overrode created_at.
        assert!(input.casts.iter().any(|(i, _)| i == "updated_at"));
    }

    #[test]
    fn touches_attribute_parses() {
        let input = ModelInput::parse(
            quote! { touches = ["post", "author"] },
            quote! { pub struct Comment { pub id: i64 } },
        )
        .unwrap();
        assert_eq!(input.touches, vec!["post".to_string(), "author".to_string()]);
    }

    // ---- Generalised DateTime auto-inject (Phase 10A polish) -------------
    //
    // The auto-inject fires per field type, not per column name. These
    // tests exercise the variations of qualified path syntax users
    // write in real code (`DateTime<Utc>` bare after `use chrono::{
    // DateTime, Utc}`, vs `chrono::DateTime<Utc>` from a non-importing
    // model, etc.) and verify the optional / collection / non-UTC
    // edge cases.

    #[test]
    fn user_datetime_field_gets_auto_as_date_time() {
        // Custom column named `last_seen_at` — not one of the
        // framework's managed timestamp columns. The generalised
        // auto-inject must still cover it because the field type
        // is `DateTime<Utc>`.
        let input = ModelInput::parse(
            quote! { timestamps = false },
            quote! {
                pub struct User {
                    pub id: i64,
                    pub last_seen_at: DateTime<Utc>,
                }
            },
        )
        .unwrap();
        let cast = input.casts.iter().find(|(i, _)| i == "last_seen_at").unwrap();
        let ty_token = &cast.1;
        let ty = quote!(#ty_token).to_string();
        assert!(
            ty.contains("AsDateTime"),
            "expected AsDateTime auto-inject on DateTime<Utc> field, got: {ty}",
        );
    }

    #[test]
    fn user_optional_datetime_field_gets_auto_as_optional_date_time() {
        let input = ModelInput::parse(
            quote! { timestamps = false },
            quote! {
                pub struct User {
                    pub id: i64,
                    pub last_seen_at: Option<DateTime<Utc>>,
                }
            },
        )
        .unwrap();
        let cast = input.casts.iter().find(|(i, _)| i == "last_seen_at").unwrap();
        let ty_token = &cast.1;
        let ty = quote!(#ty_token).to_string();
        assert!(
            ty.contains("AsOptionalDateTime"),
            "expected AsOptionalDateTime auto-inject on Option<DateTime<Utc>>, got: {ty}",
        );
    }

    #[test]
    fn user_cast_override_on_arbitrary_datetime_field_preserved() {
        // If the user explicitly declares a cast on a non-framework
        // datetime field, the auto-inject must not overwrite it.
        // Mirrors the timestamps_user_cast_override_preserved test
        // but for an arbitrary column.
        let input = ModelInput::parse(
            quote! {
                timestamps = false,
                casts = { stamp = ::suprnova::AsImmutableDateTime },
            },
            quote! {
                pub struct Audit {
                    pub id: i64,
                    pub stamp: DateTime<Utc>,
                }
            },
        )
        .unwrap();
        let cast = input.casts.iter().find(|(i, _)| i == "stamp").unwrap();
        let ty_token = &cast.1;
        let ty = quote!(#ty_token).to_string();
        assert!(
            ty.contains("AsImmutableDateTime"),
            "user-declared cast must win over auto-inject, got: {ty}",
        );
        // And the cast list must contain exactly one entry for `stamp`
        // — no double-cast.
        let count = input.casts.iter().filter(|(i, _)| i == "stamp").count();
        assert_eq!(count, 1, "expected exactly one cast for `stamp`, got {count}");
    }

    #[test]
    fn qualified_chrono_paths_match() {
        // `chrono::DateTime<chrono::Utc>` and `::chrono::DateTime<Utc>`
        // both classify as `DateTime` — the parser walks the last
        // path segment, not the qualifier.
        for ty_src in [
            "chrono::DateTime<chrono::Utc>",
            "::chrono::DateTime<Utc>",
            "DateTime<chrono::Utc>",
            "::chrono::DateTime<::chrono::Utc>",
        ] {
            let parsed: Type = syn::parse_str(ty_src).unwrap();
            assert_eq!(
                classify_datetime(&parsed),
                DateTimeShape::DateTime,
                "expected DateTime shape for `{ty_src}`",
            );
        }
    }

    #[test]
    fn non_utc_datetime_left_alone() {
        // `DateTime<Local>` / `DateTime<FixedOffset>` aren't auto-cast.
        // Users with non-UTC stamps declare the cast explicitly.
        for ty_src in [
            "DateTime<Local>",
            "DateTime<FixedOffset>",
            "chrono::DateTime<chrono::FixedOffset>",
        ] {
            let parsed: Type = syn::parse_str(ty_src).unwrap();
            assert_eq!(
                classify_datetime(&parsed),
                DateTimeShape::Other,
                "non-UTC DateTime must not auto-inject for `{ty_src}`",
            );
        }
    }

    #[test]
    fn collection_of_datetime_left_alone() {
        // `Vec<DateTime<Utc>>` and `HashMap<_, DateTime<Utc>>` need
        // their own cast — the auto-inject doesn't reach inside
        // collections.
        for ty_src in [
            "Vec<DateTime<Utc>>",
            "std::collections::HashMap<String, DateTime<Utc>>",
            "[DateTime<Utc>; 3]",
        ] {
            let parsed: Type = syn::parse_str(ty_src).unwrap();
            assert_eq!(
                classify_datetime(&parsed),
                DateTimeShape::Other,
                "collection wrapper must not classify as DateTime: `{ty_src}`",
            );
        }
    }

    #[test]
    fn primary_key_with_datetime_type_skipped() {
        // A model with a DateTime PK is unusual but legal. The
        // auto-inject must skip the PK column even when its type
        // would otherwise match — PKs are not cast-routed
        // (derive_seaorm.rs keeps PK fields in their declared type).
        let input = ModelInput::parse(
            quote! { primary_key = "stamp", key_type = "chrono::DateTime<chrono::Utc>", auto_increment = false, timestamps = false },
            quote! {
                pub struct Snapshot {
                    pub stamp: DateTime<Utc>,
                    pub data: String,
                }
            },
        )
        .unwrap();
        assert!(
            !input.casts.iter().any(|(i, _)| i == "stamp"),
            "PK column must not receive auto-injected cast",
        );
    }

    // ---- Phase 10B T1 — `relations = { ... }` parsing --------------

    #[test]
    fn parse_relations_minimal() {
        // Single HasMany — defaults FK/LK and no options.
        let input = ModelInput::parse(
            quote! {
                relations = {
                    posts: HasMany<Post>,
                }
            },
            quote! { pub struct User { pub id: i64 } },
        )
        .unwrap();
        let relations = input.relations.as_ref().unwrap();
        assert_eq!(relations.len(), 1);
        assert_eq!(relations[0].name.to_string(), "posts");
        assert!(matches!(relations[0].kind, RelationKindAttr::HasMany));
        assert!(relations[0].through.is_none());
        assert!(relations[0].options.is_empty());
    }

    #[test]
    fn parse_relations_empty_body_is_allowed() {
        // Explicit empty form `relations = {}` is legal — the model
        // declares no relations but still wires the four dispatcher
        // skeletons.
        let input = ModelInput::parse(
            quote! { relations = {} },
            quote! { pub struct User { pub id: i64 } },
        )
        .unwrap();
        let relations = input.relations.as_ref().unwrap();
        assert!(relations.is_empty(), "empty body must parse to an empty Vec");
    }

    #[test]
    fn parse_relations_with_options() {
        let input = ModelInput::parse(
            quote! {
                relations = {
                    active_posts: HasMany<Post> { fk = "owner_id", lk = "id" },
                }
            },
            quote! { pub struct User { pub id: i64 } },
        )
        .unwrap();
        let opts = &input.relations.as_ref().unwrap()[0].options;
        assert!(opts.iter().any(|o| matches!(o, RelationOpt::ForeignKey(k) if k == "owner_id")));
        assert!(opts.iter().any(|o| matches!(o, RelationOpt::LocalKey(k) if k == "id")));
    }

    #[test]
    fn parse_relations_belongs_to_many_with_pivot() {
        let input = ModelInput::parse(
            quote! {
                relations = {
                    roles: BelongsToMany<Role, RoleUserPivot> {
                        with_pivot = ["assigned_at"],
                        with_timestamps,
                    },
                }
            },
            quote! { pub struct User { pub id: i64 } },
        )
        .unwrap();
        let rel = &input.relations.as_ref().unwrap()[0];
        assert!(rel.through.is_some(), "Pivot type required for BelongsToMany");
        assert!(rel
            .options
            .iter()
            .any(|o| matches!(o, RelationOpt::WithPivot(p) if p == &vec!["assigned_at".to_string()])));
        assert!(rel
            .options
            .iter()
            .any(|o| matches!(o, RelationOpt::WithTimestamps)));
    }

    #[test]
    fn parse_relations_morph_to_with_targets() {
        let input = ModelInput::parse(
            quote! {
                relations = {
                    commentable: MorphTo { targets = [Post, Video] },
                }
            },
            quote! { pub struct Comment { pub id: i64, pub commentable_id: i64, pub commentable_type: String } },
        )
        .unwrap();
        let rel = &input.relations.as_ref().unwrap()[0];
        assert!(matches!(rel.kind, RelationKindAttr::MorphTo));
        let targets = rel
            .options
            .iter()
            .find_map(|o| match o {
                RelationOpt::MorphTargets(t) => Some(t),
                _ => None,
            })
            .expect("MorphTargets must be parsed");
        assert_eq!(targets.len(), 2);
    }

    #[test]
    fn parse_relations_morph_to_requires_targets() {
        // MorphTo with no `targets = [...]` is a declaration-site bug —
        // T6 has no targets to enumerate, and the downstream eager
        // loader / admin walker would surface a cryptic error far from
        // the source. The parser must catch this at the model
        // declaration with a message pointing at the `MorphTo` ident.
        let result = ModelInput::parse(
            quote! { relations = { commentable: MorphTo } },
            quote! { pub struct Comment { pub id: i64, pub commentable_id: i64, pub commentable_type: String } },
        );
        let err = match result {
            Ok(_) => panic!("expected MorphTo-without-targets error, got Ok"),
            Err(e) => e.to_string(),
        };
        assert!(
            err.contains("MorphTo") && err.contains("targets"),
            "expected MorphTo+targets in error message, got: {err}",
        );
    }

    #[test]
    fn parse_relations_morph_to_with_empty_options_block_still_requires_targets() {
        // `MorphTo {}` (explicit empty options block) is the same
        // failure mode — the empty block parses fine, then the
        // post-options check kicks in. Pin this so a refactor of the
        // options parser doesn't silently break the validation.
        let result = ModelInput::parse(
            quote! { relations = { commentable: MorphTo {} } },
            quote! { pub struct Comment { pub id: i64, pub commentable_id: i64, pub commentable_type: String } },
        );
        let err = match result {
            Ok(_) => panic!("expected MorphTo {{}}-without-targets error, got Ok"),
            Err(e) => e.to_string(),
        };
        assert!(
            err.contains("MorphTo") && err.contains("targets"),
            "expected MorphTo+targets in error message, got: {err}",
        );
    }

    #[test]
    fn parse_relations_rejects_unknown_kind() {
        let result = ModelInput::parse(
            quote! { relations = { bogus: NotARelation<Foo> } },
            quote! { pub struct X { pub id: i64 } },
        );
        let err = match result {
            Ok(_) => panic!("expected error, got Ok"),
            Err(e) => e.to_string(),
        };
        assert!(err.contains("unknown relation kind"), "got: {err}");
    }

    #[test]
    fn parse_relations_rejects_unknown_option() {
        let result = ModelInput::parse(
            quote! { relations = { posts: HasMany<Post> { not_a_thing = "x" } } },
            quote! { pub struct User { pub id: i64 } },
        );
        let err = match result {
            Ok(_) => panic!("expected error, got Ok"),
            Err(e) => e.to_string(),
        };
        assert!(err.contains("unknown relation option"), "got: {err}");
    }

    #[test]
    fn parse_relations_belongs_to_many_requires_pivot() {
        // `BelongsToMany<Target>` without the second generic argument
        // is a typo — surface a clear error.
        let result = ModelInput::parse(
            quote! { relations = { roles: BelongsToMany<Role> } },
            quote! { pub struct User { pub id: i64 } },
        );
        let err = match result {
            Ok(_) => panic!("expected error, got Ok"),
            Err(e) => e.to_string(),
        };
        assert!(
            err.contains("requires a second generic argument"),
            "got: {err}",
        );
    }

    #[test]
    fn parse_relations_has_many_rejects_pivot() {
        // `HasMany<Target, Pivot>` is incoherent — only m2m / Through
        // kinds take two generic args.
        let result = ModelInput::parse(
            quote! { relations = { posts: HasMany<Post, Extra> } },
            quote! { pub struct User { pub id: i64 } },
        );
        let err = match result {
            Ok(_) => panic!("expected error, got Ok"),
            Err(e) => e.to_string(),
        };
        assert!(err.contains("takes one generic argument"), "got: {err}");
    }

    #[test]
    fn parse_relations_morph_to_rejects_generics() {
        // `MorphTo<X>` is incoherent — MorphTo's targets come from
        // `targets = [...]`, not a generic argument.
        let result = ModelInput::parse(
            quote! { relations = { commentable: MorphTo<X> { targets = [Post] } } },
            quote! { pub struct Comment { pub id: i64 } },
        );
        // MorphTo doesn't allow_generics — parser will fall through
        // to options-parse path and hit the `<` as unexpected.
        assert!(result.is_err(), "MorphTo must not accept generics");
    }

    #[test]
    fn parse_relations_targets_only_on_morph_to() {
        // `targets = [...]` is MorphTo-specific.
        let result = ModelInput::parse(
            quote! { relations = { posts: HasMany<Post> { targets = [Post] } } },
            quote! { pub struct User { pub id: i64 } },
        );
        let err = match result {
            Ok(_) => panic!("expected error, got Ok"),
            Err(e) => e.to_string(),
        };
        assert!(err.contains("only valid on `MorphTo`"), "got: {err}");
    }

    #[test]
    fn parse_relations_through_keys() {
        // HasManyThrough takes A<B, C> generics + first_key / second_key
        // overrides.
        let input = ModelInput::parse(
            quote! {
                relations = {
                    country_posts: HasManyThrough<User, Post> {
                        first_key = "country_id",
                        second_key = "user_id",
                    },
                }
            },
            quote! { pub struct Country { pub id: i64 } },
        )
        .unwrap();
        let rel = &input.relations.as_ref().unwrap()[0];
        assert!(matches!(rel.kind, RelationKindAttr::HasManyThrough));
        assert!(rel.through.is_some(), "HasManyThrough has an intermediate type");
        assert!(rel
            .options
            .iter()
            .any(|o| matches!(o, RelationOpt::FirstKey(k) if k == "country_id")));
        assert!(rel
            .options
            .iter()
            .any(|o| matches!(o, RelationOpt::SecondKey(k) if k == "user_id")));
    }

    #[test]
    fn parse_relations_belongs_to_many_with_custom_pivot_columns() {
        // T4 — verify the three new pivot-customisation options parse:
        // `pivot_table` (override default `<P>::TABLE`),
        // `pivot_foreign_key` (override default `<snake(parent)>_id`),
        // `pivot_related_key` (override default `<snake(target)>_id`).
        let input = ModelInput::parse(
            quote! {
                relations = {
                    roles: BelongsToMany<Role, RolePivot> {
                        pivot_table = "role_user",
                        pivot_foreign_key = "owner_id",
                        pivot_related_key = "perm_id",
                    },
                }
            },
            quote! { pub struct User { pub id: i64 } },
        )
        .unwrap();
        let opts = &input.relations.as_ref().unwrap()[0].options;
        assert!(opts
            .iter()
            .any(|o| matches!(o, RelationOpt::PivotTable(k) if k == "role_user")));
        assert!(opts
            .iter()
            .any(|o| matches!(o, RelationOpt::PivotForeignKey(k) if k == "owner_id")));
        assert!(opts
            .iter()
            .any(|o| matches!(o, RelationOpt::PivotRelatedKey(k) if k == "perm_id")));
    }

    #[test]
    fn parse_relations_multiple_entries() {
        let input = ModelInput::parse(
            quote! {
                relations = {
                    profile: HasOne<Profile>,
                    posts: HasMany<Post>,
                    role: BelongsTo<Role>,
                }
            },
            quote! { pub struct User { pub id: i64 } },
        )
        .unwrap();
        let relations = input.relations.as_ref().unwrap();
        assert_eq!(relations.len(), 3);
        assert_eq!(relations[0].name.to_string(), "profile");
        assert_eq!(relations[1].name.to_string(), "posts");
        assert_eq!(relations[2].name.to_string(), "role");
    }
}
