// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by `suprnova db:sync` - Changes will be overwritten
// Add custom code to src/models/todos.rs instead

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "todos")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub description: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

// Note: Relation enum is required here for DeriveEntityModel macro.
// Define your actual relations in src/models/todos.rs using the Related trait.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
