//! `#[derive(Factory)]` — auto-generate a Laravel-style factory marker
//! struct for a model.
//!
//! Applied to a model struct (one that derives `fake::Dummy`), the
//! derive emits a sibling marker type — `User` → `pub struct UserFactory;`
//! — and an `impl ::suprnova::Factory for UserFactory` that calls
//! `Faker.fake::<User>()` for its `definition()`. The user gets the
//! fluent builder surface (`UserFactory::new().count(10).create_many()`)
//! without writing the wrapper struct by hand.
//!
//! Override the generated name via `#[factory(name = "CustomFactory")]`.
//!
//! v1 only supports plain structs. Enums, unions, and generic models
//! fail to compile with a clear error message — generics in particular
//! would require deciding how the factory type parameterizes, which is
//! out of scope until a real use case shows up.

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{parse_macro_input, DeriveInput, Expr, Lit};

#[derive(Default)]
struct FactoryAttrs {
    /// Override for the generated marker struct name.
    /// Defaults to `<ModelName>Factory`.
    name: Option<String>,
}

fn parse_attrs(input: &DeriveInput) -> syn::Result<FactoryAttrs> {
    let mut attrs = FactoryAttrs::default();

    for attribute in &input.attrs {
        if !attribute.path().is_ident("factory") {
            continue;
        }

        attribute.parse_nested_meta(|nested| {
            let key = nested
                .path
                .get_ident()
                .ok_or_else(|| nested.error("expected identifier key in #[factory(...)]"))?
                .to_string();

            let value: Expr = nested.value()?.parse()?;
            let Expr::Lit(expr_lit) = &value else {
                return Err(nested.error(format!(
                    "`{key}` in #[factory(...)] expects a string literal"
                )));
            };
            let Lit::Str(s) = &expr_lit.lit else {
                return Err(nested.error(format!(
                    "`{key}` in #[factory(...)] expects a string literal"
                )));
            };
            let v = s.value();

            match key.as_str() {
                "name" => attrs.name = Some(v),
                other => {
                    return Err(nested.error(format!(
                        "unknown key `{other}` in #[factory(...)] — supported keys: name"
                    )));
                }
            }
            Ok(())
        })?;
    }

    Ok(attrs)
}

pub fn derive_factory_impl(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    // v1 scope: plain (non-generic) structs only.
    if !matches!(input.data, syn::Data::Struct(_)) {
        return syn::Error::new_spanned(
            &input.ident,
            "#[derive(Factory)] can only be applied to structs",
        )
        .to_compile_error()
        .into();
    }
    if !input.generics.params.is_empty() {
        return syn::Error::new_spanned(
            &input.generics,
            "#[derive(Factory)] does not support generic models. \
             Generics force a decision about how the factory type \
             parameterizes — file a real-use-case bug if you need this.",
        )
        .to_compile_error()
        .into();
    }

    let attrs = match parse_attrs(&input) {
        Ok(a) => a,
        Err(e) => return e.to_compile_error().into(),
    };

    let model_ident = &input.ident;
    let factory_name = attrs
        .name
        .unwrap_or_else(|| format!("{}Factory", model_ident));
    let factory_ident = format_ident!("{}", factory_name);
    let vis = &input.vis;

    let expanded = quote! {
        #[doc = concat!(
            "Factory for [`",
            stringify!(#model_ident),
            "`] — generated by `#[derive(Factory)]`. Call `",
            stringify!(#factory_ident),
            "::new()` to get a fluent builder."
        )]
        #vis struct #factory_ident;

        impl ::suprnova::Factory for #factory_ident {
            type Model = #model_ident;

            fn definition() -> Self::Model {
                use ::suprnova::__fake::Fake;
                ::suprnova::__fake::Faker.fake::<Self::Model>()
            }
        }
    };

    expanded.into()
}
