//! `#[derive(Factory)]` — auto-generate a Laravel-style factory marker
//! struct for a model.
//!
//! Applied to a model struct (one that derives `fake::Dummy`), the
//! derive emits a sibling marker type — `User` → `pub struct UserFactory;`
//! — and an `impl ::suprnova::Factory for UserFactory` that calls
//! `Faker.fake::<User>()` for its `definition()`. The user gets the
//! fluent builder surface (`UserFactory::new().count(10).create_many()`)
//! without writing the wrapper struct by hand.
//!
//! Override the generated name via `#[factory(name = "CustomFactory")]`.
//!
//! v1 only supports plain structs. Enums, unions, and generic models
//! fail to compile with a clear error message — generics in particular
//! would require deciding how the factory type parameterizes, which is
//! out of scope until a real use case shows up.

use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{DeriveInput, Expr, Lit, parse_macro_input};

#[derive(Default)]
struct FactoryAttrs {
    /// Override for the generated marker struct name.
    /// Defaults to `<ModelName>Factory`.
    name: Option<String>,
}

fn parse_attrs(input: &DeriveInput) -> syn::Result<FactoryAttrs> {
    let mut attrs = FactoryAttrs::default();

    for attribute in &input.attrs {
        if !attribute.path().is_ident("factory") {
            continue;
        }

        attribute.parse_nested_meta(|nested| {
            let key = nested
                .path
                .get_ident()
                .ok_or_else(|| nested.error("expected identifier key in #[factory(...)]"))?
                .to_string();

            let value: Expr = nested.value()?.parse()?;
            let Expr::Lit(expr_lit) = &value else {
                return Err(nested.error(format!(
                    "`{key}` in #[factory(...)] expects a string literal"
                )));
            };
            let Lit::Str(s) = &expr_lit.lit else {
                return Err(nested.error(format!(
                    "`{key}` in #[factory(...)] expects a string literal"
                )));
            };
            let v = s.value();

            match key.as_str() {
                "name" => {
                    // Domain 5 audit M-D5-7 — the `name = "..."` value
                    // is emitted as `format_ident!("{}", factory_name)`
                    // at the bottom of `derive_factory_impl` to declare
                    // a new `pub struct <Name>;` type. A non-ident
                    // value (`name = "User Factory"`, `name =
                    // "user-factory"`) panics the macro instead of
                    // producing a clean compile error.
                    if syn::parse_str::<syn::Ident>(&v).is_err() {
                        return Err(nested.error(format!(
                            "`name = \"{v}\"` in #[factory(...)] — must parse as a Rust \
                             identifier (type name) because the macro emits \
                             `pub struct {v};`. Use a CamelCase name without spaces / \
                             dashes (e.g. \"CustomFactory\")."
                        )));
                    }
                    attrs.name = Some(v);
                }
                other => {
                    return Err(nested.error(format!(
                        "unknown key `{other}` in #[factory(...)] — supported keys: name"
                    )));
                }
            }
            Ok(())
        })?;
    }

    Ok(attrs)
}

pub fn derive_factory_impl(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    // v1 scope: plain (non-generic) structs only.
    if !matches!(input.data, syn::Data::Struct(_)) {
        return syn::Error::new_spanned(
            &input.ident,
            "#[derive(Factory)] can only be applied to structs",
        )
        .to_compile_error()
        .into();
    }
    if !input.generics.params.is_empty() {
        return syn::Error::new_spanned(
            &input.generics,
            "#[derive(Factory)] does not support generic models. \
             Generics force a decision about how the factory type \
             parameterizes — file a real-use-case bug if you need this.",
        )
        .to_compile_error()
        .into();
    }

    let attrs = match parse_attrs(&input) {
        Ok(a) => a,
        Err(e) => return e.to_compile_error().into(),
    };

    let model_ident = &input.ident;
    let factory_name = attrs
        .name
        .unwrap_or_else(|| format!("{}Factory", model_ident));
    let factory_ident = format_ident!("{}", factory_name);
    let vis = &input.vis;

    let expanded = quote! {
        #[doc = concat!(
            "Factory for [`",
            stringify!(#model_ident),
            "`] — generated by `#[derive(Factory)]`. Call `",
            stringify!(#factory_ident),
            "::new()` to get a fluent builder."
        )]
        #vis struct #factory_ident;

        impl ::suprnova::Factory for #factory_ident {
            type Model = #model_ident;

            fn definition() -> Self::Model {
                use ::suprnova::__fake::Fake;
                ::suprnova::__fake::Faker.fake::<Self::Model>()
            }
        }
    };

    expanded.into()
}

#[cfg(test)]
mod tests {
    //! Domain 5 audit M-D5-7 regression: the `#[factory(name = "...")]`
    //! value used to be forced into a Rust ident via
    //! `format_ident!("{}", factory_name)` at expand time with no
    //! parse-time check. A user typo (`name = "User Factory"`) panicked
    //! the macro; after the fix, parse_attrs rejects with a clean
    //! span-pointed error.
    use super::*;
    use syn::parse_quote;

    #[test]
    fn factory_name_with_space_rejected() {
        let input: DeriveInput = parse_quote! {
            #[factory(name = "User Factory")]
            pub struct User;
        };
        let err = parse_attrs(&input)
            .err()
            .expect("name with space must reject");
        let msg = err.to_string();
        assert!(
            msg.contains("User Factory"),
            "error must name the bad value; got: {msg}",
        );
        assert!(
            msg.contains("Rust identifier"),
            "error must explain WHY the value is bad; got: {msg}",
        );
    }

    #[test]
    fn factory_name_with_dash_rejected() {
        let input: DeriveInput = parse_quote! {
            #[factory(name = "user-factory")]
            pub struct User;
        };
        let err = parse_attrs(&input)
            .err()
            .expect("name with dash must reject");
        let msg = err.to_string();
        assert!(msg.contains("user-factory"), "got: {msg}");
    }

    #[test]
    fn factory_valid_camelcase_name_accepted() {
        let input: DeriveInput = parse_quote! {
            #[factory(name = "CustomFactory")]
            pub struct User;
        };
        let attrs = parse_attrs(&input).expect("valid name must parse");
        assert_eq!(attrs.name.as_deref(), Some("CustomFactory"));
    }

    #[test]
    fn factory_no_attribute_uses_default() {
        // Bare struct — no #[factory] attribute. Default name path
        // (`<ModelName>Factory`) kicks in downstream; parse_attrs just
        // returns None here.
        let input: DeriveInput = parse_quote! {
            pub struct User;
        };
        let attrs = parse_attrs(&input).expect("no attribute is legal");
        assert!(attrs.name.is_none());
    }
}
