// This file is auto-generated by Suprnova. Do not edit manually.
// Run `suprnova generate-types` to regenerate.

export interface HomeProps {
  title: string;
  message: string;
}

// Authentication types
export interface LoginProps {
  errors?: {
    email?: string[];
    password?: string[];
  };
}

export interface RegisterProps {
  errors?: {
    name?: string[];
    email?: string[];
    password?: string[];
    password_confirmation?: string[];
  };
}

export interface DashboardProps {
  user: {
    id: number;
    name: string;
    email: string;
  };
}
