//! Integration tests for the `FormRequest` impl generated by `#[derive(Data)]`.
//!
//! `hyper::body::Incoming` cannot be constructed outside hyper, so these tests
//! bind a one-shot TCP listener, run `CreateUserDto::extract` inside the handler
//! service, capture the `Result<CreateUserDto, FrameworkError>` via
//! `Arc<Mutex<Option<…>>>`, and assert on it after the round-trip completes.
//! This mirrors the pattern used in `framework/tests/precognition.rs`.

use std::convert::Infallible;
use std::net::SocketAddr;
use std::sync::{Arc, Mutex};

use http_body_util::Full;
use hyper::body::Bytes;
use hyper::server::conn::http1;
use hyper::service::service_fn;
use hyper_util::rt::TokioIo;

use suprnova::error::FrameworkError;
use suprnova::{FormRequest, HttpResponse, Request};

#[derive(Debug, suprnova::Data, validator::Validate)]
struct CreateUserDto {
    #[validate(email)]
    pub email: String,

    #[data(input_only)]
    #[validate(length(min = 8))]
    pub password: String,
}

/// Spawn a one-shot server that calls `CreateUserDto::extract`, captures the
/// `Result`, then returns a stub 200. The captured result is asserted by the
/// calling test after the round-trip.
async fn spawn_and_capture() -> (SocketAddr, Arc<Mutex<Option<Result<CreateUserDto, FrameworkError>>>>) {
    let captured: Arc<Mutex<Option<Result<CreateUserDto, FrameworkError>>>> =
        Arc::new(Mutex::new(None));
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = listener.local_addr().unwrap();

    let captured_server = captured.clone();
    tokio::spawn(async move {
        if let Ok((stream, _)) = listener.accept().await {
            let io = TokioIo::new(stream);
            let captured_svc = captured_server.clone();
            let svc = service_fn(
                move |hyper_req: hyper::Request<hyper::body::Incoming>| {
                    let captured_inner = captured_svc.clone();
                    async move {
                        let req = Request::new(hyper_req);
                        let result = CreateUserDto::extract(req).await;
                        *captured_inner.lock().unwrap() = Some(result);
                        Ok::<_, Infallible>(
                            HttpResponse::text("ok").into_hyper(),
                        )
                    }
                },
            );
            let _ = http1::Builder::new().serve_connection(io, svc).await;
        }
    });

    (addr, captured)
}

async fn post_json(addr: SocketAddr, body: serde_json::Value) -> () {
    let stream = tokio::net::TcpStream::connect(addr).await.unwrap();
    let io = TokioIo::new(stream);
    let (mut sender, conn) = hyper::client::conn::http1::handshake::<_, Full<Bytes>>(io)
        .await
        .unwrap();
    tokio::spawn(async move {
        let _ = conn.await;
    });

    let body_bytes = serde_json::to_vec(&body).unwrap();
    let req = hyper::Request::builder()
        .method("POST")
        .uri("http://localhost/users")
        .header("content-type", "application/json")
        .header("content-length", body_bytes.len())
        .body(Full::new(Bytes::from(body_bytes)))
        .unwrap();

    // Fire-and-forget: we only need the server to process the request.
    let _ = sender.send_request(req).await;
}

#[tokio::test]
async fn data_struct_extracts_as_form_request() {
    let (addr, captured) = spawn_and_capture().await;
    post_json(
        addr,
        serde_json::json!({"email": "ada@example.com", "password": "secretkey"}),
    )
    .await;

    // Give the server time to process (it's already serialised via channel
    // boundary, but a brief yield ensures the spawned task stores the result).
    tokio::task::yield_now().await;

    let result = captured.lock().unwrap().take().expect("server did not process request");
    let dto = result.unwrap();
    assert_eq!(dto.email, "ada@example.com");
    assert_eq!(dto.password, "secretkey");
}

#[tokio::test]
async fn data_struct_form_request_rejects_invalid_payload() {
    let (addr, captured) = spawn_and_capture().await;
    post_json(
        addr,
        serde_json::json!({"email": "not-an-email", "password": "short"}),
    )
    .await;

    tokio::task::yield_now().await;

    let result = captured.lock().unwrap().take().expect("server did not process request");
    let err = result.unwrap_err();
    assert_eq!(
        err.status_code(),
        422,
        "expected 422 Unprocessable Entity for invalid input, got {}",
        err.status_code()
    );
}
